# Netlify Configuration File

# Settings for Netlify build
[build]
  command = "npm run build"
  publish = ".next"
  
  # Configurações de ambiente
  [build.environment]
    PYTHON_VERSION = "3.9.7"
    NODE_VERSION = "18"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Netlify CMS configuration
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Identity settings for Netlify CMS
[template.environment]
  NETLIFY_IDENTITY_WIDGET = "true"
